name: Feature request
description: An idea for one of the mods
title: "[Mod] Short description"
labels: [enhancement]
body:
  - type: dropdown
    id: mod
    attributes:
      label: Mod
      options:
        - Ghost Car
        - Fine Choke Control
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: The idea
      description: What should the mod do, and when would you use it?
    validations:
      required: true
